#!/usr/bin/env bash
# Pings IP 5 times passed as an argument
# String in our argument

IP="${1}"
fn=$(basename "${BASH_SOURCE[@]}")

if ! ["$IP" ]; then
echo "Usage: ${fn} {IP_ADDRESS}"
else
ping -c 5 "${IP}"
fi
