#!/usr/bin/env bash
# This script groups visitors by IP address and HTTP status and displays the code

# Using awk to group and count occurences, then sorting data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
