#!/usr/bin/env bash
# This script is displaying "Best School" ten times using while loop

# Initialize a counter
counter=0

# Using a while loop
while [ $counter -lt 10 ]; do
	echo "Best School"
	((counter++))
done
