#!/usr/bin/env bash
# This script displays "Best School" ten times but says hi at the 9th 

# Initialize a counter
counter=0

# Using a while loop
while [ $counter -lt 10 ]; do
	# Checks if its the 9th iteration
	if [ $counter -eq 8 ]; then 
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
		((counter++))
done
	
