#!/usr/bin/env bash
# This script displays different messages for different loop iterations

# Initialize a counter 
 counter=1

# Using a while loop to iterate from 1 to 10
while [ $counter -le 10 ]; do
	# Checks condition for different messages
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	# Increment the counter
	((counter++))
done
