#!/usr/bin/env bash
# This script displays the content of a current in a list format

# Using for loop to iterate over files in the current directory
for file in *; do
	# Check if the file is a regular file(not a symbolic or directory)
	if [ -f "$file" ]; then
		# Extract the part of name after the fist dash
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
