#!/usr/bin/env bash
# This script checks information in the school file
file_path="school"

# Checks if the file exists
if [ -e "$file_path" ]; then
	echo "school file exists"

	# Check if the file is empty
	if [ -s "$file_path" ]; then
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
