#!/usr/bin/env bash

# Stop apache if its running
pkill apache2

# Create nginx user and group
if ! id -u nginx &>/dev/null; then
	useradd -r -s /sbin/nologin nginx
fi

# Change ownership of nginx configuration files to nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/sutes-available
chown -R nginx:nginx /etc/nginx/sites-enabled

# Change permission of nginx configuration files
chmod 640 /etc/nginx/nginx.conf
chmod 640 /etc/nginx/sites-available*
chmod 640 /etc/nginx/sites-enabled*

# Replace port 80 with port 8080 in default nginx conf
sed -i 's/listen 80;/listen 8080;g' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart
